name: aac_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  flutter_tts: ^3.3.0
  fluttertoast: ^8.0.9
  path_provider: ^2.0.11
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  intl_utils: ^2.8.7
  provider: ^6.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.1
  cloud_firestore: ^5.4.1
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.20.0
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  intl_utils: ^2.6.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/phrases_en.json
    - assets/phrases_zh.json
    - assets/phrases_ms.json
    - assets/phrases_ja.json

    - assets/images/test.png
    - assets/images/people/people.png
    - assets/images/things/things.png
    - assets/images/actions/actions.png
    - assets/images/places/places.png
    - assets/images/food/food.png
    - assets/images/feelings/feelings.png
    - assets/images/descriptive/descriptive.png
    - assets/images/questions/questions.png
    - assets/images/time/time.png
    - assets/images/social/social.png
    - assets/images/health/health.png

    - assets/images/people/I.png
    - assets/images/people/you.png
    - assets/images/people/me.png
    - assets/images/people/we.png
    - assets/images/people/he.png
    - assets/images/people/she.png
    - assets/images/people/they.png
    - assets/images/people/them.png
    - assets/images/people/us.png
    - assets/images/people/friend.png
    - assets/images/people/family.png
    - assets/images/people/stranger.png
    - assets/images/people/teacher.png
    - assets/images/people/mom.png
    - assets/images/people/dad.png
    - assets/images/people/brother.png
    - assets/images/people/sister.png
    - assets/images/people/nurse.png
    - assets/images/people/caregiver.png

    - assets/images/things/chair.png
    - assets/images/things/car.png
    - assets/images/things/book.png
    - assets/images/things/pen.png
    - assets/images/things/table.png
    - assets/images/things/phone.png
    - assets/images/things/computer.png
    - assets/images/things/bed.png
    - assets/images/things/cup.png
    - assets/images/things/bag.png
    - assets/images/things/watch.png
    - assets/images/things/glass.png
    - assets/images/things/wallet.png
    - assets/images/things/key.png
    - assets/images/things/ipad.png
    - assets/images/things/stuff.png
    - assets/images/things/it.png
    - assets/images/things/this.png
    - assets/images/things/that.png


    - assets/images/actions/eat.png
    - assets/images/actions/drink.png
    - assets/images/actions/sleep.png
    - assets/images/actions/play.png
    - assets/images/actions/run.png
    - assets/images/actions/walk.png
    - assets/images/actions/jump.png
    - assets/images/actions/help.png
    - assets/images/actions/read.png
    - assets/images/actions/listen.png
    - assets/images/actions/talk.png
    - assets/images/actions/sing.png
    - assets/images/actions/dance.png
    - assets/images/actions/swim.jpeg
    - assets/images/actions/stop.png
    - assets/images/actions/see.jpeg
    - assets/images/actions/go.png
    - assets/images/actions/look.png
    - assets/images/actions/come.png
    - assets/images/actions/put.jpeg
    - assets/images/actions/sit.png
    - assets/images/actions/open.png
    - assets/images/actions/start.jpeg
    - assets/images/actions/wait.png
    - assets/images/actions/watch.jpeg
    - assets/images/actions/wash.jpeg
    - assets/images/actions/turn.jpeg
    - assets/images/actions/stay.jpeg

    - assets/images/actions2/actions2.jpeg
    - assets/images/actions2/want.png
    - assets/images/actions2/say.png
    - assets/images/actions2/get.png
    - assets/images/actions2/take.png
    - assets/images/actions2/make.png
    - assets/images/actions2/know.png
    - assets/images/actions2/have.png
    - assets/images/actions2/tell.png
    - assets/images/actions2/tell.png
    - assets/images/actions2/show.png

    - assets/images/places/here.png
    - assets/images/places/there.png
    - assets/images/places/home.png
    - assets/images/places/school.png
    - assets/images/places/park.png
    - assets/images/places/store.png
    - assets/images/places/library.png
    - assets/images/places/restaurant.png
    - assets/images/places/hospital.png
    - assets/images/places/gym.png
    - assets/images/places/beach.png
    - assets/images/places/office.png
    - assets/images/places/hotel.png
    - assets/images/places/shop.png

    - assets/images/food/apple.png
    - assets/images/food/banana.png
    - assets/images/food/carrot.png
    - assets/images/food/juice.png
    - assets/images/food/water.png
    - assets/images/food/bread.png
    - assets/images/food/milk.png
    - assets/images/food/cheese.png
    - assets/images/food/chicken.png
    - assets/images/food/pizza.png
    - assets/images/food/rice.png
    - assets/images/food/pasta.png
    - assets/images/food/yogurt.png
    - assets/images/food/grapes.png
    - assets/images/food/orange.png
    - assets/images/food/sandwich.jpeg
    - assets/images/food/salad.png
    - assets/images/food/fish.png
    - assets/images/food/cake.png
    - assets/images/food/fruit.png
    - assets/images/food/snack.png
    - assets/images/food/dinner.png
    - assets/images/food/lunch.png
    - assets/images/food/breakfast.png


    - assets/images/feelings/happy.png
    - assets/images/feelings/sad.png
    - assets/images/feelings/excited.png
    - assets/images/feelings/scared.png
    - assets/images/feelings/angry.png
    - assets/images/feelings/tired.png
    - assets/images/feelings/bored.png
    - assets/images/feelings/surprised.png
    - assets/images/feelings/nervous.png
    - assets/images/feelings/calm.png
    - assets/images/feelings/worried.png
    - assets/images/feelings/safe.png
    - assets/images/feelings/confused.png

    - assets/images/descriptive/red.png
    - assets/images/descriptive/blue.png
    - assets/images/descriptive/green.png
    - assets/images/descriptive/big.png
    - assets/images/descriptive/small.png
    - assets/images/descriptive/soft.png
    - assets/images/descriptive/hard.png
    - assets/images/descriptive/hot.png
    - assets/images/descriptive/cold.png
    - assets/images/descriptive/fast.png
    - assets/images/descriptive/slow.png
    - assets/images/descriptive/loud.png
    - assets/images/descriptive/quiet.png
    - assets/images/descriptive/heavy.png
    - assets/images/descriptive/light.png
    - assets/images/descriptive/good.png
    - assets/images/descriptive/different.jpg
    - assets/images/descriptive/same.png
    - assets/images/descriptive/nice.png
    - assets/images/descriptive/favorite.png
    - assets/images/descriptive/old.png
    - assets/images/descriptive/dirty.png
    - assets/images/descriptive/wet.png
    - assets/images/descriptive/bad.png
    - assets/images/descriptive/little.png
    - assets/images/descriptive/disgusting.png
    - assets/images/descriptive/fun.png
    - assets/images/descriptive/funny.png
    - assets/images/descriptive/new.png

    - assets/images/questions/what.png
    - assets/images/questions/where.png
    - assets/images/questions/when.png
    - assets/images/questions/how.png
    - assets/images/questions/why.png
    - assets/images/questions/who.png
    - assets/images/questions/which.png
    - assets/images/questions/can_i.png
    - assets/images/questions/do_you.png
    - assets/images/questions/is_it.png
  
    - assets/images/time/morning.png
    - assets/images/time/afternoon.png
    - assets/images/time/evening.png
    - assets/images/time/night.png
    - assets/images/time/today.png
    - assets/images/time/tomorrow.png
    - assets/images/time/yesterday.png
    - assets/images/time/now.png
    - assets/images/time/later.png
    - assets/images/time/soon.png
  
    - assets/images/social/hello.png
    - assets/images/social/goodbye.png
    - assets/images/social/please.png
    - assets/images/social/thank_you.png
    - assets/images/social/sorry.png
    - assets/images/social/how_are_you.png
    - assets/images/social/i_need_help.png
    - assets/images/social/nice_to_meet_you.png
    - assets/images/social/excuse_me.png
    - assets/images/social/i_don't_understand.png
    - assets/images/social/can_you_repeat_that.png
    - assets/images/social/what's_your_name.png
    - assets/images/social/i'm_lost.png
    - assets/images/social/i'm_hungry.png
    - assets/images/social/i'm_thirsty.png
  
    - assets/images/health/head.png
    - assets/images/health/arm.png
    - assets/images/health/leg.png
    - assets/images/health/medicine.png
    - assets/images/health/doctor.png
    - assets/images/health/sick.png
    - assets/images/health/hurt.png
    - assets/images/health/stomach.png
    - assets/images/health/back.png
    - assets/images/health/ear.png
    - assets/images/health/eye.png
    - assets/images/health/nose.png
    - assets/images/health/throat.png
    - assets/images/health/cough.png
    - assets/images/health/fever.png

    - assets/images/transportation/transportation.png
    - assets/images/transportation/bus.png
    - assets/images/transportation/train.png
    - assets/images/transportation/bicycle.png
    - assets/images/transportation/taxi.png
    - assets/images/transportation/walking.png
    - assets/images/transportation/car.png

    - assets/images/weather/weather.png
    - assets/images/weather/sunny.png
    - assets/images/weather/rainy.png
    - assets/images/weather/cloudy.png
    - assets/images/weather/windy.png
    - assets/images/weather/snowy.png
    - assets/images/weather/hot.png
    - assets/images/weather/cold.png

    - assets/images/animals/animals.png
    - assets/images/animals/dog.png
    - assets/images/animals/cat.png
    - assets/images/animals/bird.png
    - assets/images/animals/horse.png

    - assets/images/numbers/numbers.jpg
    - assets/images/numbers/0.png
    - assets/images/numbers/1.jpeg
    - assets/images/numbers/2.png
    - assets/images/numbers/3.png
    - assets/images/numbers/4.png
    - assets/images/numbers/5.png
    - assets/images/numbers/6.png
    - assets/images/numbers/7.png
    - assets/images/numbers/8.jpeg
    - assets/images/numbers/9.png

    - assets/images/punctuation/punctuation.png
    - assets/images/punctuation/period.png
    - assets/images/punctuation/question_mark.png
    - assets/images/punctuation/exclamation_mark.png
    - assets/images/punctuation/comma.png


    - lib/l10n/

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
